/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { AbiJoinPool, AbiJoinPoolInterface } from "../AbiJoinPool";

const _abi = [
  {
    payable: true,
    stateMutability: "payable",
    type: "fallback",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address payable",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "transferBNB",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
];

export class AbiJoinPool__factory {
  static readonly abi = _abi;
  static createInterface(): AbiJoinPoolInterface {
    return new utils.Interface(_abi) as AbiJoinPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AbiJoinPool {
    return new Contract(address, _abi, signerOrProvider) as AbiJoinPool;
  }
}
