export const CONSUMABLE_STATUS = {
  IDLE: 'idle',
  LISTED: 'listed',
  LISTING: 'listing',
  BUYING: 'buying',
  UNLISTED: 'unlisted',
  UNLISTING: 'unlisting',
  UPDATING: 'updating',
  PURCHASED: 'purchased',
  TRANSFERING: 'transfering',
  IMPORTING: 'importing',
  IMPORTED: 'imported',
  IN_GAME_IMPORTING: 'ingame_importing',
  WITHDRAWING: 'withdrawing',
  OPENING: 'opening',
}
